name: "Always Fast"
description: "Performance Regression for PRs"

inputs:
  main_branch:
    description: "Main Branch"
    required: true
    default: "main"
  influxdb_url:
    description: "InfluxDB URL"
    required: true
    default: "http://ziade.org:8086"
  influxdb_org:
    description: "InfluxDB Organization"
    required: true
    default: "acme"
  influxdb_bucket:
    description: "InfluxDB bucket"
    required: true
    default: "benchmarks"
  github_token:
    description: "Github Token"
    required: true
    default: "${{ github.token }}"
  influxdb_token:
    description: "InfluxDB Token"
    required: true
  pr_number:
    description: "PR number"
    required: false
    default: "${{ github.event.pull_request.number || github.event.number }}"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GIT_BRANCH: ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
    MAIN_BRANCH: ${{ inputs.main_branch }}
    INFLUXDB_URL: ${{ inputs.influxdb_url }}
    INFLUXDB_ORG: ${{ inputs.influxdb_org }}
    INFLUXDB_BUCKET: ${{ inputs.influxdb_bucket }}
