name: "Always Fast"
description: "Performance Regression for PRs"

inputs:
  main_branch:
    description: "Main Branch"
    required: true
    default: "main"
  influxdb_url:
    description: "InfluxDB URL"
    required: true
    default: "http://localhost:8086"
  influxdb_org:
    description: "InfluxDB Organization"
    required: true
    default: "acme"
  influxdb_bucket:
    description: "InfluxDB bucket"
    required: true
    default: "benchmarks"
  github_token:
    description: "Github Token"
    required: true
    default: "${{ github.token }}"
  influxdb_token:
    description: "InfluxDB Token"
    required: true
  github_repository:
    description: "Github repository"
    required: true
    default: "${{github.repository}}"
  github_comment:
    description: "Github comment"
    default: "${{ github.event.comment.body || github.event.pull_request.body || 'empty'}}"
  head_ref:
    description: "Head ref"
    required: true
  pr_number:
    description: "pr number"
    default: ${{ github.event.issue.number }}

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    MAIN_BRANCH: ${{ inputs.main_branch }}
    INFLUXDB_URL: ${{ inputs.influxdb_url }}
    INFLUXDB_ORG: ${{ inputs.influxdb_org }}
    INFLUXDB_BUCKET: ${{ inputs.influxdb_bucket }}
    INFLUXDB_TOKEN: ${{ inputs.influxdb_token }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_REPOSITORY: ${{ inputs.github_repository }}
    GITHUB_COMMENT: ${{ inputs.github_comment }}
    HEAD_REF: ${{ inputs.head_ref }}
    PR_NUMBER: ${{ inputs.pr_number }}
